### ISSUE TITLE
Makefile.Linux should support CPPFLAGS/LDFLAGS

### ISSUE THREAD

**Issue by vapier** [mtk09422/chromiumos-third_party-mediatek-datool#1]
this section should respect CPPFLAGS & LDFLAGS:

<pre>
$(TARGET):$(SOURCES)
    $(CC) $(SOURCES) $(CFLAGS) -I$(INCLUDES) -o $@
</pre>

the $(SOURCES) should also be after all the flags, so i guess move it to the end

**Comment by mtk09422** [comment]
Makefile revised
